name: Auto-export Draw.io Diagrams

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Draw.io CLI
        run: npm install -g @jgraph/drawio-cli

      - name: Export PNG from Draw.io Files
        run: |
          for file in $(find . -name "*.drawio"); do
            echo "Exporting $file to PNG"
            drawio --export --format png "$file" --output "${file%.drawio}.png"
          done

      - name: Commit and Push PNG Files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-export PNG from Draw.io diagrams" || echo "No changes to commit"
          git push
