name: Render .drawio files

on:
  push:
    paths:
      - "stronger_system_diagram.drawio"  # Only run when the stronger_system_diagram.drawio is updated

jobs:
  render_drawio:
    runs-on: ubuntu-latest
    name: Render .drawio files
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache Docker Layers
      uses: actions/cache@v3
      with:
        path: /tmp/.docker-layer-cache  # Path to cache Docker layers
        key: ${{ runner.os }}-docker-ghcr-render-drawio-v1
        restore-keys: |
          ${{ runner.os }}-docker-
          
    - name: Set Up Docker Layer Cache
      run: mkdir -p /tmp/.docker-layer-cache
      
    - name: Render .drawio files
      uses: docker://ghcr.io/racklet/render-drawio-action:v1
      with:
        formats: 'svg'  # Output format (can be changed to png, pdf, etc.)
        sub-dirs: '.'  # Scan current directory for the specified file
        skip-dirs: '.git'  # Skip .git directory
        log-level: 'info'  # Verbose logging
      id: render
      
    - name: Update README with SVG
      run: |
        sed -i 's|!\[System Design Diagram\](stronger_system_diagram.svg)|![System Design Diagram](./stronger_system_diagram.svg)|g' README.md

    - name: Commit the rendered files and README
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actor  # Use the GitHub actor as commit author
        message: 'Automatically render stronger_system_diagram.drawio and update README'
        add: |
          stronger_system_diagram.svg
          README.md
      if: "${{ steps.render.outputs.rendered-files != ''}}"
